"""Voice Guide AI — Configuration package."""

from config.constants import (
    SUPPORTED_LANGUAGES,
    DEFAULT_LANGUAGE,
    FALLBACK_LANGUAGE,
    DIALOGUE_STATES,
    DIALOGUE_REQUIRED_KEYS,
    TRANSLATION_REQUIRED_KEYS,
    MAX_HISTORY_ENTRIES,
    MAX_REPLAY_COUNT,
    STATUS_ACTIVE,
    STATUS_INACTIVE,
    STATUS_DRAFT,
)
from config.environment import Environment
from config.exceptions import (
    VoiceGuideError,
    ConfigurationError,
    PathNotFoundError,
    FileReadError,
    FileWriteError,
    JSONParseError,
    JSONValidationError,
    DuplicateIDError,
    UnsupportedLanguageError,
    TranslationNotFoundError,
    DialogueNotFoundError,
    DialogueValidationError,
    DialogueConditionError,
    DialogueStateError,
    DialogueEngineError,
    HistoryError,
)
from config.logger import get_logger, setup_logging, log_performance, perf_block
from config.paths import PATHS, Paths
from config.settings import SETTINGS, Settings

__all__ = [
    "SUPPORTED_LANGUAGES",
    "DEFAULT_LANGUAGE",
    "FALLBACK_LANGUAGE",
    "DIALOGUE_STATES",
    "DIALOGUE_REQUIRED_KEYS",
    "TRANSLATION_REQUIRED_KEYS",
    "MAX_HISTORY_ENTRIES",
    "MAX_REPLAY_COUNT",
    "STATUS_ACTIVE",
    "STATUS_INACTIVE",
    "STATUS_DRAFT",
    "Environment",
    "VoiceGuideError",
    "ConfigurationError",
    "PathNotFoundError",
    "FileReadError",
    "FileWriteError",
    "JSONParseError",
    "JSONValidationError",
    "DuplicateIDError",
    "UnsupportedLanguageError",
    "TranslationNotFoundError",
    "DialogueNotFoundError",
    "DialogueValidationError",
    "DialogueConditionError",
    "DialogueStateError",
    "DialogueEngineError",
    "HistoryError",
    "get_logger",
    "setup_logging",
    "log_performance",
    "perf_block",
    "PATHS",
    "Paths",
    "SETTINGS",
    "Settings",
]
