# Generated by Django 5.2.17 on 2026-09-06 08:56

import apps.procurement.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("procurement", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CapacityReservation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reservation_date", models.DateField()),
                ("quantity_kg", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("RELEASED", "Released"), ("CONSUMED", "Consumed")], default="ACTIVE", max_length=12)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("procurement_center", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="capacity_reservations", to="procurement.procurementcenter")),
                ("released_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="capacity_reservations_released", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-reservation_date", "created_at"]},
        ),
        migrations.CreateModel(
            name="ProcurementRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("request_number", models.CharField(default=apps.procurement.models.generate_request_number, editable=False, max_length=20, unique=True)),
                ("intended_quantity_kg", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),
                ("preferred_date", models.DateField()),
                ("farmer_notes", models.TextField(blank=True, max_length=500)),
                ("status", models.CharField(choices=[("SUBMITTED", "Submitted"), ("UNDER_REVIEW", "Under review"), ("APPROVED", "Approved"), ("RESCHEDULED", "Rescheduled"), ("REJECTED", "Rejected"), ("CANCELLED", "Cancelled"), ("EXPIRED", "Expired")], default="SUBMITTED", max_length=20)),
                ("submitted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True, max_length=500)),
                ("farmer", models.ForeignKey(limit_choices_to={"role": "FARMER"}, on_delete=django.db.models.deletion.PROTECT, related_name="procurement_requests", to=settings.AUTH_USER_MODEL)),
                ("farmer_crop", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="procurement_requests", to="procurement.farmercrop")),
                ("procurement_center", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="procurement_requests", to="procurement.procurementcenter")),
                ("reviewed_by", models.ForeignKey(blank=True, limit_choices_to={"role__in": ["PROCUREMENT_OFFICER", "ADMIN"]}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="procurement_requests_reviewed", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-submitted_at", "request_number"]},
        ),
        migrations.CreateModel(
            name="ProcurementAppointment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("scheduled_date", models.DateField()),
                ("slot_start_time", models.TimeField()),
                ("slot_end_time", models.TimeField()),
                ("queue_number", models.PositiveIntegerField()),
                ("token_code", models.CharField(default=apps.procurement.models.generate_token_code, editable=False, max_length=15, unique=True)),
                ("status", models.CharField(choices=[("SCHEDULED", "Scheduled"), ("CANCELLED", "Cancelled")], default="SCHEDULED", max_length=12)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("capacity_reservation", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="appointment", to="procurement.capacityreservation")),
                ("procurement_center", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="procurement_appointments", to="procurement.procurementcenter")),
                ("request", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="appointments", to="procurement.procurementrequest")),
            ],
            options={"ordering": ["scheduled_date", "slot_start_time", "queue_number"]},
        ),
        migrations.AddField(
            model_name="capacityreservation",
            name="request",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="capacity_reservations", to="procurement.procurementrequest"),
        ),
        migrations.CreateModel(
            name="RequestStatusEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("from_status", models.CharField(blank=True, choices=[("SUBMITTED", "Submitted"), ("UNDER_REVIEW", "Under review"), ("APPROVED", "Approved"), ("RESCHEDULED", "Rescheduled"), ("REJECTED", "Rejected"), ("CANCELLED", "Cancelled"), ("EXPIRED", "Expired")], max_length=20)),
                ("to_status", models.CharField(choices=[("SUBMITTED", "Submitted"), ("UNDER_REVIEW", "Under review"), ("APPROVED", "Approved"), ("RESCHEDULED", "Rescheduled"), ("REJECTED", "Rejected"), ("CANCELLED", "Cancelled"), ("EXPIRED", "Expired")], max_length=20)),
                ("note", models.TextField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="procurement_request_events", to=settings.AUTH_USER_MODEL)),
                ("request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="status_events", to="procurement.procurementrequest")),
            ],
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.AddIndex(
            model_name="procurementrequest",
            index=models.Index(fields=["farmer", "status"], name="request_farmer_status_idx"),
        ),
        migrations.AddIndex(
            model_name="procurementrequest",
            index=models.Index(fields=["procurement_center", "status", "preferred_date"], name="request_center_status_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="procurementrequest",
            constraint=models.CheckConstraint(condition=models.Q(("intended_quantity_kg__gt", 0)), name="request_quantity_gt_zero"),
        ),
        migrations.AddIndex(
            model_name="procurementappointment",
            index=models.Index(fields=["procurement_center", "scheduled_date", "status"], name="appointment_center_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="procurementappointment",
            constraint=models.CheckConstraint(condition=models.Q(("slot_start_time__lt", models.F("slot_end_time"))), name="appointment_start_before_end"),
        ),
        migrations.AddConstraint(
            model_name="procurementappointment",
            constraint=models.UniqueConstraint(condition=models.Q(("status", "SCHEDULED")), fields=("request",), name="one_scheduled_appt_request"),
        ),
        migrations.AddConstraint(
            model_name="procurementappointment",
            constraint=models.UniqueConstraint(fields=("procurement_center", "scheduled_date", "queue_number"), name="unique_center_date_queue"),
        ),
        migrations.AddIndex(
            model_name="capacityreservation",
            index=models.Index(fields=["procurement_center", "reservation_date", "status"], name="reservation_center_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="capacityreservation",
            constraint=models.CheckConstraint(condition=models.Q(("quantity_kg__gt", 0)), name="reservation_quantity_gt_zero"),
        ),
        migrations.AddConstraint(
            model_name="capacityreservation",
            constraint=models.UniqueConstraint(condition=models.Q(("status", "ACTIVE")), fields=("request",), name="one_active_reservation_request"),
        ),
        migrations.AddIndex(
            model_name="requeststatusevent",
            index=models.Index(fields=["request", "created_at"], name="request_event_time_idx"),
        ),
    ]
