# Generated by Django 5.2.17 on 2026-09-06 09:53

import apps.procurement.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("procurement", "0002_capacityreservation_procurementrequest_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcceptanceDecision",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("outcome", models.CharField(choices=[("ACCEPTED", "Accepted"), ("PARTIAL", "Partially accepted"), ("REJECTED", "Rejected")], max_length=8)),
                ("accepted_quantity_kg", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ("rejected_quantity_kg", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ("decision_reason", models.TextField(blank=True, max_length=500)),
                ("decided_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={"ordering": ["-decided_at"]},
        ),
        migrations.CreateModel(
            name="ArrivalCheckIn",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("transport_mode", models.CharField(choices=[("TRACTOR", "Tractor"), ("TRUCK", "Truck"), ("PICKUP", "Pickup vehicle"), ("OTHER", "Other")], default="TRACTOR", max_length=12)),
                ("vehicle_number", models.CharField(blank=True, max_length=20)),
                ("arrival_notes", models.TextField(blank=True, max_length=500)),
                ("checked_in_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={"ordering": ["-checked_in_at"]},
        ),
        migrations.CreateModel(
            name="ProcurementReceipt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("receipt_number", models.CharField(default=apps.procurement.models.generate_receipt_number, editable=False, max_length=20, unique=True)),
                ("verification_code", models.CharField(default=apps.procurement.models.generate_verification_code, editable=False, max_length=16, unique=True)),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={"ordering": ["-issued_at"]},
        ),
        migrations.CreateModel(
            name="ProcurementTransaction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("transaction_number", models.CharField(default=apps.procurement.models.generate_transaction_number, editable=False, max_length=20, unique=True)),
                ("accepted_quantity_kg", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),
                ("rate_per_kg", models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),
                ("acceptance_notes", models.TextField(blank=True, max_length=500)),
                ("procured_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={"ordering": ["-procured_at", "transaction_number"]},
        ),
        migrations.CreateModel(
            name="QualityInspection",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("result", models.CharField(choices=[("PASSED", "Passed"), ("REJECTED", "Rejected")], max_length=8)),
                ("grade", models.CharField(choices=[("FAQ", "Fair Average Quality"), ("GRADE_A", "Grade A"), ("GRADE_B", "Grade B"), ("OTHER", "Other"), ("NA", "Not applicable")], default="FAQ", max_length=8)),
                ("moisture_percentage", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ("foreign_matter_percentage", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ("damaged_percentage", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ("sample_reference", models.CharField(blank=True, max_length=60)),
                ("inspection_notes", models.TextField(blank=True, max_length=500)),
                ("rejection_reason", models.TextField(blank=True, max_length=500)),
                ("inspected_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={"ordering": ["-inspected_at"]},
        ),
        migrations.CreateModel(
            name="Weighment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("gross_weight_kg", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),
                ("tare_weight_kg", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ("net_weight_kg", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),
                ("bag_count", models.PositiveIntegerField(blank=True, null=True)),
                ("weighbridge_reference", models.CharField(blank=True, max_length=60)),
                ("weighment_notes", models.TextField(blank=True, max_length=500)),
                ("weighed_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={"ordering": ["-weighed_at"]},
        ),
        migrations.RemoveConstraint(model_name="procurementappointment", name="one_scheduled_appt_request"),
        migrations.AddField(model_name="capacityreservation", name="consumed_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(
            model_name="capacityreservation",
            name="consumed_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="capacity_reservations_consumed", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="procurementappointment",
            name="status",
            field=models.CharField(choices=[("SCHEDULED", "Scheduled"), ("CHECKED_IN", "Checked in"), ("COMPLETED", "Completed"), ("REJECTED", "Rejected"), ("CANCELLED", "Cancelled")], default="SCHEDULED", max_length=12),
        ),
        migrations.AlterField(
            model_name="procurementrequest",
            name="status",
            field=models.CharField(choices=[("SUBMITTED", "Submitted"), ("UNDER_REVIEW", "Under review"), ("APPROVED", "Approved"), ("RESCHEDULED", "Rescheduled"), ("REJECTED", "Rejected"), ("CANCELLED", "Cancelled"), ("EXPIRED", "Expired"), ("CHECKED_IN", "Checked in"), ("INSPECTION_PASSED", "Inspection passed"), ("INSPECTION_REJECTED", "Inspection rejected"), ("WEIGHED", "Weighed"), ("PROCURED", "Procured"), ("PROCUREMENT_REJECTED", "Procurement rejected")], default="SUBMITTED", max_length=20),
        ),
        migrations.AlterField(
            model_name="requeststatusevent",
            name="from_status",
            field=models.CharField(blank=True, choices=[("SUBMITTED", "Submitted"), ("UNDER_REVIEW", "Under review"), ("APPROVED", "Approved"), ("RESCHEDULED", "Rescheduled"), ("REJECTED", "Rejected"), ("CANCELLED", "Cancelled"), ("EXPIRED", "Expired"), ("CHECKED_IN", "Checked in"), ("INSPECTION_PASSED", "Inspection passed"), ("INSPECTION_REJECTED", "Inspection rejected"), ("WEIGHED", "Weighed"), ("PROCURED", "Procured"), ("PROCUREMENT_REJECTED", "Procurement rejected")], max_length=20),
        ),
        migrations.AlterField(
            model_name="requeststatusevent",
            name="to_status",
            field=models.CharField(choices=[("SUBMITTED", "Submitted"), ("UNDER_REVIEW", "Under review"), ("APPROVED", "Approved"), ("RESCHEDULED", "Rescheduled"), ("REJECTED", "Rejected"), ("CANCELLED", "Cancelled"), ("EXPIRED", "Expired"), ("CHECKED_IN", "Checked in"), ("INSPECTION_PASSED", "Inspection passed"), ("INSPECTION_REJECTED", "Inspection rejected"), ("WEIGHED", "Weighed"), ("PROCURED", "Procured"), ("PROCUREMENT_REJECTED", "Procurement rejected")], max_length=20),
        ),
        migrations.AddConstraint(
            model_name="procurementappointment",
            constraint=models.UniqueConstraint(condition=models.Q(("status__in", ["SCHEDULED", "CHECKED_IN"])), fields=("request",), name="one_open_appt_request"),
        ),
        migrations.AddField(
            model_name="acceptancedecision",
            name="decided_by",
            field=models.ForeignKey(limit_choices_to={"role__in": ["PROCUREMENT_OFFICER", "ADMIN"]}, on_delete=django.db.models.deletion.PROTECT, related_name="acceptance_decisions_recorded", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(model_name="arrivalcheckin", name="appointment", field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="check_in", to="procurement.procurementappointment")),
        migrations.AddField(model_name="arrivalcheckin", name="checked_in_by", field=models.ForeignKey(limit_choices_to={"role__in": ["PROCUREMENT_OFFICER", "ADMIN"]}, on_delete=django.db.models.deletion.PROTECT, related_name="arrival_check_ins_recorded", to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name="arrivalcheckin", name="procurement_center", field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="arrival_check_ins", to="procurement.procurementcenter")),
        migrations.AddField(model_name="arrivalcheckin", name="request", field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="check_in", to="procurement.procurementrequest")),
        migrations.AddField(model_name="procurementtransaction", name="acceptance_decision", field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="procurement_transaction", to="procurement.acceptancedecision")),
        migrations.AddField(model_name="procurementtransaction", name="appointment", field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="procurement_transaction", to="procurement.procurementappointment")),
        migrations.AddField(model_name="procurementtransaction", name="farmer", field=models.ForeignKey(limit_choices_to={"role": "FARMER"}, on_delete=django.db.models.deletion.PROTECT, related_name="procurement_transactions", to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name="procurementtransaction", name="farmer_crop", field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="procurement_transactions", to="procurement.farmercrop")),
        migrations.AddField(model_name="procurementtransaction", name="procurement_center", field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="procurement_transactions", to="procurement.procurementcenter")),
        migrations.AddField(model_name="procurementtransaction", name="recorded_by", field=models.ForeignKey(limit_choices_to={"role__in": ["PROCUREMENT_OFFICER", "ADMIN"]}, on_delete=django.db.models.deletion.PROTECT, related_name="procurement_transactions_recorded", to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name="procurementtransaction", name="request", field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="procurement_transaction", to="procurement.procurementrequest")),
        migrations.AddField(model_name="procurementreceipt", name="transaction", field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="receipt", to="procurement.procurementtransaction")),
        migrations.AddField(model_name="qualityinspection", name="check_in", field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="inspection", to="procurement.arrivalcheckin")),
        migrations.AddField(model_name="qualityinspection", name="inspected_by", field=models.ForeignKey(limit_choices_to={"role__in": ["PROCUREMENT_OFFICER", "ADMIN"]}, on_delete=django.db.models.deletion.PROTECT, related_name="quality_inspections_recorded", to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name="weighment", name="inspection", field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="weighment", to="procurement.qualityinspection")),
        migrations.AddField(model_name="weighment", name="weighed_by", field=models.ForeignKey(limit_choices_to={"role__in": ["PROCUREMENT_OFFICER", "ADMIN"]}, on_delete=django.db.models.deletion.PROTECT, related_name="weighments_recorded", to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name="acceptancedecision", name="weighment", field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="acceptance_decision", to="procurement.weighment")),
        migrations.AddIndex(model_name="arrivalcheckin", index=models.Index(fields=["procurement_center", "checked_in_at"], name="checkin_center_time_idx")),
        migrations.AddIndex(model_name="procurementtransaction", index=models.Index(fields=["farmer", "procured_at"], name="transaction_farmer_time_idx")),
        migrations.AddIndex(model_name="procurementtransaction", index=models.Index(fields=["procurement_center", "procured_at"], name="transaction_center_time_idx")),
        migrations.AddConstraint(model_name="procurementtransaction", constraint=models.CheckConstraint(condition=models.Q(("accepted_quantity_kg__gt", 0)), name="transaction_accepted_gt_zero")),
        migrations.AddConstraint(model_name="procurementtransaction", constraint=models.CheckConstraint(condition=models.Q(("rate_per_kg__gt", 0)), name="transaction_rate_gt_zero")),
        migrations.AddConstraint(model_name="procurementtransaction", constraint=models.CheckConstraint(condition=models.Q(("total_amount__gt", 0)), name="transaction_total_gt_zero")),
        migrations.AddConstraint(model_name="qualityinspection", constraint=models.CheckConstraint(condition=models.Q(("moisture_percentage__isnull", True), models.Q(("moisture_percentage__gte", 0), ("moisture_percentage__lte", 100)), _connector="OR"), name="inspection_moisture_range")),
        migrations.AddConstraint(model_name="qualityinspection", constraint=models.CheckConstraint(condition=models.Q(("foreign_matter_percentage__isnull", True), models.Q(("foreign_matter_percentage__gte", 0), ("foreign_matter_percentage__lte", 100)), _connector="OR"), name="inspection_foreign_range")),
        migrations.AddConstraint(model_name="qualityinspection", constraint=models.CheckConstraint(condition=models.Q(("damaged_percentage__isnull", True), models.Q(("damaged_percentage__gte", 0), ("damaged_percentage__lte", 100)), _connector="OR"), name="inspection_damaged_range")),
        migrations.AddConstraint(model_name="weighment", constraint=models.CheckConstraint(condition=models.Q(("gross_weight_kg__gt", models.F("tare_weight_kg"))), name="weighment_gross_gt_tare")),
        migrations.AddConstraint(model_name="weighment", constraint=models.CheckConstraint(condition=models.Q(("net_weight_kg__gt", 0)), name="weighment_net_gt_zero")),
        migrations.AddConstraint(model_name="acceptancedecision", constraint=models.CheckConstraint(condition=models.Q(("accepted_quantity_kg__gte", 0)), name="decision_accepted_gte_zero")),
        migrations.AddConstraint(model_name="acceptancedecision", constraint=models.CheckConstraint(condition=models.Q(("rejected_quantity_kg__gte", 0)), name="decision_rejected_gte_zero")),
        migrations.AddConstraint(model_name="acceptancedecision", constraint=models.CheckConstraint(condition=models.Q(models.Q(("accepted_quantity_kg", 0), ("outcome", "REJECTED")), models.Q(("accepted_quantity_kg__gt", 0), ("outcome__in", ["ACCEPTED", "PARTIAL"])), _connector="OR"), name="decision_outcome_quantity")),
    ]
