# Generated by Django 5.2.17 on 2026-09-06

import apps.procurement.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("procurement", "0003_acceptancedecision_arrivalcheckin_procurementreceipt_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Grievance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("grievance_number", models.CharField(default=apps.procurement.models.generate_grievance_number, editable=False, max_length=20, unique=True)),
                ("category", models.CharField(choices=[("SCHEDULING", "Scheduling"), ("QUALITY", "Quality inspection"), ("PROCUREMENT", "Procurement"), ("PAYMENT", "Payment"), ("OTHER", "Other")], max_length=16)),
                ("subject", models.CharField(max_length=160)),
                ("description", models.TextField(max_length=2000)),
                ("priority", models.CharField(choices=[("LOW", "Low"), ("NORMAL", "Normal"), ("HIGH", "High")], default="NORMAL", max_length=8)),
                ("status", models.CharField(choices=[("OPEN", "Open"), ("UNDER_REVIEW", "Under review"), ("RESOLVED", "Resolved"), ("REJECTED", "Rejected")], default="OPEN", max_length=16)),
                ("resolution", models.TextField(blank=True, max_length=2000)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("assigned_to", models.ForeignKey(blank=True, limit_choices_to={"role__in": ["PROCUREMENT_OFFICER", "ADMIN"]}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="grievances_assigned", to=settings.AUTH_USER_MODEL)),
                ("farmer", models.ForeignKey(limit_choices_to={"role": "FARMER"}, on_delete=django.db.models.deletion.PROTECT, related_name="grievances", to=settings.AUTH_USER_MODEL)),
                ("request", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="grievances", to="procurement.procurementrequest")),
                ("transaction", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="grievances", to="procurement.procurementtransaction")),
            ],
            options={"ordering": ["-created_at", "grievance_number"]},
        ),
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("payment_number", models.CharField(default=apps.procurement.models.generate_payment_number, editable=False, max_length=20, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),
                ("method", models.CharField(choices=[("DBT", "Direct Benefit Transfer"), ("NEFT", "NEFT"), ("RTGS", "RTGS"), ("OTHER", "Other")], default="DBT", max_length=8)),
                ("beneficiary_reference", models.CharField(default="Verified farmer account", max_length=120)),
                ("status", models.CharField(choices=[("INITIATED", "Initiated"), ("PROCESSING", "Processing"), ("SETTLED", "Settled"), ("FAILED", "Failed")], default="INITIATED", max_length=12)),
                ("attempt_count", models.PositiveIntegerField(default=1)),
                ("initiated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("processing_at", models.DateTimeField(blank=True, null=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("last_failed_at", models.DateTimeField(blank=True, null=True)),
                ("bank_reference", models.CharField(blank=True, max_length=80)),
                ("last_failure_reason", models.TextField(blank=True, max_length=500)),
                ("initiated_by", models.ForeignKey(limit_choices_to={"role__in": ["PROCUREMENT_OFFICER", "ADMIN"]}, on_delete=django.db.models.deletion.PROTECT, related_name="payments_initiated", to=settings.AUTH_USER_MODEL)),
                ("transaction", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="payment", to="procurement.procurementtransaction")),
            ],
            options={"ordering": ["-initiated_at", "payment_number"]},
        ),
        migrations.CreateModel(
            name="PaymentReceipt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("receipt_number", models.CharField(default=apps.procurement.models.generate_payment_receipt_number, editable=False, max_length=20, unique=True)),
                ("verification_code", models.CharField(default=apps.procurement.models.generate_verification_code, editable=False, max_length=16, unique=True)),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("issued_by", models.ForeignKey(limit_choices_to={"role": "ADMIN"}, on_delete=django.db.models.deletion.PROTECT, related_name="payment_receipts_issued", to=settings.AUTH_USER_MODEL)),
                ("payment", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="settlement_receipt", to="procurement.paymentrecord")),
            ],
            options={"ordering": ["-issued_at"]},
        ),
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("action", models.CharField(choices=[("INITIATE", "Initiate"), ("START_PROCESSING", "Start processing"), ("SETTLE", "Settle"), ("FAIL", "Fail"), ("RETRY", "Retry")], max_length=20)),
                ("from_status", models.CharField(blank=True, choices=[("INITIATED", "Initiated"), ("PROCESSING", "Processing"), ("SETTLED", "Settled"), ("FAILED", "Failed")], max_length=12)),
                ("to_status", models.CharField(choices=[("INITIATED", "Initiated"), ("PROCESSING", "Processing"), ("SETTLED", "Settled"), ("FAILED", "Failed")], max_length=12)),
                ("note", models.TextField(blank=True, max_length=500)),
                ("external_reference", models.CharField(blank=True, max_length=80)),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                ("payload_fingerprint", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payment_events_recorded", to=settings.AUTH_USER_MODEL)),
                ("payment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="events", to="procurement.paymentrecord")),
            ],
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("category", models.CharField(choices=[("APPOINTMENT", "Appointment"), ("QUALITY", "Quality"), ("PROCUREMENT", "Procurement"), ("PAYMENT", "Payment"), ("GRIEVANCE", "Grievance"), ("SYSTEM", "System")], max_length=16)),
                ("title", models.CharField(max_length=160)),
                ("message", models.TextField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("grievance", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="notifications", to="procurement.grievance")),
                ("recipient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to=settings.AUTH_USER_MODEL)),
                ("request", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="notifications", to="procurement.procurementrequest")),
                ("transaction", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="notifications", to="procurement.procurementtransaction")),
                ("payment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="notifications", to="procurement.paymentrecord")),
            ],
            options={"ordering": ["-created_at", "id"]},
        ),
        migrations.AddField(
            model_name="grievance",
            name="payment",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="grievances", to="procurement.paymentrecord"),
        ),
        migrations.CreateModel(
            name="GrievanceEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("action", models.CharField(choices=[("CREATED", "Created"), ("START_REVIEW", "Start review"), ("RESOLVE", "Resolve"), ("REJECT", "Reject")], max_length=16)),
                ("from_status", models.CharField(blank=True, choices=[("OPEN", "Open"), ("UNDER_REVIEW", "Under review"), ("RESOLVED", "Resolved"), ("REJECTED", "Rejected")], max_length=16)),
                ("to_status", models.CharField(choices=[("OPEN", "Open"), ("UNDER_REVIEW", "Under review"), ("RESOLVED", "Resolved"), ("REJECTED", "Rejected")], max_length=16)),
                ("note", models.TextField(blank=True, max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="grievance_events_recorded", to=settings.AUTH_USER_MODEL)),
                ("grievance", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="events", to="procurement.grievance")),
            ],
            options={"ordering": ["created_at", "id"], "indexes": [models.Index(fields=["grievance", "created_at"], name="grievance_event_time_idx")]},
        ),
        migrations.AddIndex(model_name="paymentrecord", index=models.Index(fields=["status", "initiated_at"], name="payment_status_time_idx")),
        migrations.AddConstraint(model_name="paymentrecord", constraint=models.CheckConstraint(condition=models.Q(("amount__gt", 0)), name="payment_amount_gt_zero")),
        migrations.AddConstraint(model_name="paymentrecord", constraint=models.CheckConstraint(condition=models.Q(("attempt_count__gte", 1)), name="payment_attempt_gte_one")),
        migrations.AddConstraint(model_name="paymentrecord", constraint=models.UniqueConstraint(condition=models.Q(("bank_reference", ""), _negated=True), fields=("bank_reference",), name="unique_nonblank_bank_reference")),
        migrations.AddIndex(model_name="paymentevent", index=models.Index(fields=["payment", "created_at"], name="payment_event_time_idx")),
        migrations.AddIndex(model_name="notification", index=models.Index(fields=["recipient", "read_at", "created_at"], name="notification_inbox_idx")),
        migrations.AddIndex(model_name="grievance", index=models.Index(fields=["farmer", "status"], name="grievance_farmer_status_idx")),
        migrations.AddIndex(model_name="grievance", index=models.Index(fields=["status", "priority", "created_at"], name="grievance_queue_idx")),
    ]
