import express, { Response } from 'express';
import { AuthenticatedRequest, authenticate } from '../middleware/auth';
import { FarmerCropRequest } from '../models/FarmerCropRequest';
import { AIRecommendation } from '../models/AIRecommendation';
import { runRecommendationEngine } from '../services/recommendationEngine';
import { findSimilarRecommendation } from '../services/similaritySearch';
import { callOpenAIForCrops } from '../services/openaiService';

const router = express.Router();

// POST /api/crop-recommendation
router.post('/', authenticate, async (req: AuthenticatedRequest, res: Response) => {
  try {
    const {
      farmArea, areaUnit, state, district, village,
      soilType, soilPH, organicCarbon, nitrogen, phosphorus, potassium, ecValue,
      waterAvailability, irrigationType, rainfall, averageTemperature,
      season, farmingType, budget, previousCrop, preferredCrop,
    } = req.body;

    // Validate required fields
    if (!farmArea || !state || !district || !soilType || !soilPH || !waterAvailability || !irrigationType || !season || !budget) {
      return res.status(400).json({ error: 'Missing required fields' });
    }

    const farmerId = req.user!.userId;

    // Save the farmer request
    const farmerRequest = await FarmerCropRequest.create({
      farmerId, farmArea, areaUnit, state, district, village,
      soilType, soilPH, organicCarbon, nitrogen, phosphorus, potassium, ecValue,
      waterAvailability, irrigationType, rainfall, averageTemperature,
      season, farmingType, budget, previousCrop, preferredCrop,
    });

    const conditions = {
      soilType, soilPH: Number(soilPH), waterAvailability, season,
      district, state, farmArea: Number(farmArea),
      budget: Number(budget), farmingType: farmingType || 'conventional',
      rainfall: rainfall ? Number(rainfall) : undefined,
      averageTemperature: averageTemperature ? Number(averageTemperature) : undefined,
    };

    // Step 1: Similarity search in existing AIRecommendations
    const similar = await findSimilarRecommendation(conditions);
    if (similar.found) {
      return res.json({
        success: true,
        source: 'database',
        similarityScore: similar.similarityScore,
        requestId: farmerRequest._id,
        recommendations: similar.recommendations,
        message: 'Recommendations retrieved from cached data',
      });
    }

    // Step 2: Run local recommendation engine
    const { recommendations, hasHighScore } = await runRecommendationEngine(farmerRequest);

    if (hasHighScore && recommendations.length >= 3) {
      // Save to AIRecommendations for future reuse
      const saved = await AIRecommendation.create({
        farmerConditions: conditions,
        recommendations,
        source: 'database',
        requestId: farmerRequest._id.toString(),
      });

      return res.json({
        success: true,
        source: 'database',
        requestId: farmerRequest._id,
        recommendationId: saved._id,
        recommendations,
        message: 'Recommendations generated from crop knowledge base',
      });
    }

    // Step 3: Fallback to OpenAI GPT
    const aiRecommendations = await callOpenAIForCrops(conditions);

    const saved = await AIRecommendation.create({
      farmerConditions: conditions,
      recommendations: aiRecommendations,
      source: 'openai',
      requestId: farmerRequest._id.toString(),
    });

    return res.json({
      success: true,
      source: 'openai',
      requestId: farmerRequest._id,
      recommendationId: saved._id,
      recommendations: aiRecommendations,
      message: 'Recommendations generated by AI',
    });

  } catch (error: any) {
    console.error('Crop recommendation error:', error);
    res.status(500).json({ error: error.message || 'Failed to generate recommendations' });
  }
});

// GET /api/crop-recommendation/history
router.get('/history', authenticate, async (req: AuthenticatedRequest, res: Response) => {
  try {
    const farmerId = req.user!.userId;
    const page = parseInt(req.query.page as string) || 1;
    const limit = parseInt(req.query.limit as string) || 10;

    const requests = await FarmerCropRequest.find({ farmerId })
      .sort({ createdAt: -1 })
      .skip((page - 1) * limit)
      .limit(limit);

    const total = await FarmerCropRequest.countDocuments({ farmerId });

    // Attach recommendations to each request
    const history = await Promise.all(
      requests.map(async (request) => {
        const aiRec = await AIRecommendation.findOne({ requestId: request._id.toString() });
        return {
          request,
          recommendations: aiRec?.recommendations || [],
          source: aiRec?.source || null,
          recommendationId: aiRec?._id || null,
        };
      })
    );

    res.json({ success: true, data: history, total, page, limit });
  } catch (error) {
    res.status(500).json({ error: 'Failed to fetch history' });
  }
});

// GET /api/crop-recommendation/:id
router.get('/:id', authenticate, async (req: AuthenticatedRequest, res: Response) => {
  try {
    const recommendation = await AIRecommendation.findById(req.params.id);
    if (!recommendation) {
      return res.status(404).json({ error: 'Recommendation not found' });
    }
    const request = await FarmerCropRequest.findById(recommendation.requestId);
    res.json({ success: true, data: { recommendation, request } });
  } catch (error) {
    res.status(500).json({ error: 'Failed to fetch recommendation' });
  }
});

// POST /api/crop-recommendation/feedback
router.post('/feedback', authenticate, async (req: AuthenticatedRequest, res: Response) => {
  try {
    const { recommendationId, feedback, feedbackNote } = req.body;

    if (!recommendationId || !feedback) {
      return res.status(400).json({ error: 'recommendationId and feedback are required' });
    }

    if (!['helpful', 'not_helpful'].includes(feedback)) {
      return res.status(400).json({ error: 'feedback must be helpful or not_helpful' });
    }

    const updated = await AIRecommendation.findByIdAndUpdate(
      recommendationId,
      { feedback, feedbackNote: feedbackNote || '' },
      { new: true }
    );

    if (!updated) {
      return res.status(404).json({ error: 'Recommendation not found' });
    }

    res.json({ success: true, message: 'Feedback recorded', data: updated });
  } catch (error) {
    res.status(500).json({ error: 'Failed to save feedback' });
  }
});

export default router;
